version: '3.8'
services:
  web:
    build: .
    ports:
      - 5000:5000
      - 5678:5678
    volumes:
      - ./app:/app
    entrypoint:
      [
        "python",
        "-m",
        "debugpy",
        "--listen",
        "0.0.0.0:5678",
        "-m",
        "app",
        "--wait-for-client",
        "--multiprocess",
        "-m",
        "flask",
        "run",
        "-h",
        "0.0.0.0",
        "-p",
        "5000"
      ]
